# fly.toml app configuration file generated for bean on 2024-10-03T11:00:36-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bean'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1